apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: mongo:4.2.5
          name: db
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
