apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: {{.Values.mongo_uri}}
 #             value: mongodb://{{ .Release.Name }}-demo-app-db/test
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}-{{ .Chart.Name }}
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
