apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "demo-app-backend.fullname" . }}
  name: {{ include "demo-app-backend.fullname" . }}
spec:
  type: LoadBalancer #default ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ include "demo-app-backend.fullname" . }}
