apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tiller-role
  namespace: localtest
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]
