apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "app.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.targetPort }}
{{- if hasKey .Values.service "nodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name | quote }}