apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo-app
  name: demo-app
spec:
  type: ClusterIP #default anyways
  ports:
    - protocol: "TCP" #default anyways
      port: 8080
      targetPort: 8080
  selector:
    app: demo-app
