apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-app-ingress
spec:
  rules:
    - host: fortune.test
      http:
        paths:
          - path: /
            backend:
              serviceName: demo-app
              servicePort: 8080
