apiVersion: v1
appVersion: 1.0.0
description: Helm chart for deploying basic applications
name: generic-chart
keywords:
- helm
sources:
  - https://github.com/dhananjay12/learn-helm/generic-chart
version: 0.0.1
maintainers:
  - name: dhananjay
