replicaCount: 1

image:
  repository: dhananjay12/angular-test-versioning
  tag: 1.1.0
  pullPolicy: Always

containerPort: 80

service:
  httpPort: 80
  targetPort: 80

## Disable if not require
# Follow readme to install nginx
ingress:
  enabled: false
  annotations:
    "kubernetes.io/ingress.class": "nginx"
    "nginx.ingress.kubernetes.io/proxy-body-size": "50m"
    "nginx.ingress.kubernetes.io/ssl-redirect": "false"
  hosts:
    - host: "kubernetes.docker.internal"
      paths:
        - /

