apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: demo-app
  name: demo-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        run: demo-app
    spec:
      containers:
        - image: dhananjay12/demo-app:1.0.0
          name: demo-app
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
      restartPolicy: Always
status: {}
