apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "demo-app-db.fullname" . }}
  name: {{ include "demo-app-db.fullname" . }}
spec:
  ports:
    - name: db
      port: 27017
      targetPort: 27017
  selector:
    app: {{ include "demo-app-db.fullname" . }}
